networks:
  evoe-network:
    driver: bridge

volumes:
  mysql-vol: {}

services:
  react:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: evoe-react:latest
    command: yarn dev
    ports:
      - "3000:3000"
    depends_on:
      - node-api
      - mysql
    networks:
      - evoe-network
    volumes:
      - ./client:/app
    env_file:
      - .env

  node-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: evoe-node-api:latest
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - evoe-network
    command: yarn dev
    volumes:
      - ./api:/app

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    ports:
      - "3306:3306"
    volumes:
      - mysql-vol:/var/lib/mysql
    networks:
      - evoe-network
