name: CI Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint-format:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_ROOT_HOST: "%"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Create API .env file
        working-directory: ./api
        run: |
          cat <<EOF > .env
          PORT=${{ secrets.PORT }}
          MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER=${{ secrets.MYSQL_USER }}
          EOF

      - name: Wait for MySQL
        timeout-minutes: 1
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..4}; do  # Aumente o número de tentativas
            if mysqladmin ping -h mysql -P 3306 -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} --protocol=tcp --silent; then
              echo "MySQL is ready!"
              exit 0
            fi
            echo "Attempt $i/8: MySQL not ready. Retrying in 10 seconds..."
            sleep 10
          done
          echo "MySQL failed to start within timeout"
          exit 1

      - name: Run API lint fix and format
        working-directory: ./api
        run: yarn lint:fix && yarn format

      - name: Run Client lint fix and format
        working-directory: ./client
        run: yarn lint:fix && yarn format
