name: CI Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Create API .env file
        working-directory: ./api
        run: |
          cat <<EOF > .env
          PORT=${{ secrets.PORT }}
          MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER=${{ secrets.MYSQL_USER }}
          EOF

      - name: Install API dependencies
        working-directory: ./api
        run: yarn install --frozen-lockfile

      - name: Run API lint fix and format
        working-directory: ./api
        run: yarn lint:fix && yarn format

      - name: Install Client dependencies
        working-directory: ./client
        run: yarn install --frozen-lockfile

      - name: Run Client lint fix and format
        working-directory: ./client
        run: yarn lint:fix && yarn format
